### PR TITLE
Module 1: Block 3: Day 2

### PR DESCRIPTION
**Pull request by porag-m06**
### Portfolio: accessibility Checked:
Web Accessibility Easy Checks report:

Page titles - No issues found.
Image text alternatives - Three out missing alt text are added.
Text headings - No issues found. 
Color contrast - No issues found. 
Resize (Text) - No issues found.
Interaction (labels are optional but recommended as voiceover tools can read them, and should be set as invisible to match the Figma design)- No issues found.
Moving content - No issues found.
Multimedia - No issues found.
The basic structure of the page - No issues found.

### CODE REVIEW

**Review by wayungi — CHANGES_REQUESTED** [review]
Hi @porag-m06 , 

image

**Congratulations on the good job done so far!** 🤝 

There are some issues that you still need to work on to go to the next project but you are almost there! 😄 

## Highlights ⚡ ⚡ 
- [ ] The report includes all areas required to be tested 💯 


## Required Changes ♻️
_Check the comments under the review._
-  [ ] Good work improving the accessibility of your webpage, I found some issues that  I am suggesting you fix before moving on to the next project 
btn
logo
project

**To reproduce these results so that you can fix them, Please use [this aditus tool](https://www.aditus.io/button-contrast-checker/) to help to check the colour contrast of the project.**

- [ ] I have noticed that the interaction of your page is not fully functional. I can tab through all your links but only the **porgfollo**  responds. I cannot navigate to the **About** & **Contact** sections of the page. Kindly fix this.
links
 - [OPTIONAL ] is it a typo or you actually intended to have a navigation item called **porgfollo** 🤔 ?

**PLEASE NOTE** since this is a pair programming task and you may need to make more than one change, I would suggest you collaborate with your partner.
Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by porag-m06** [comment]
Hi, @wayungi, thank you so much for the review. However, about the button contract the color of the text and background was picked as indicated on the Figma design. Do we need to change the color to get passed on the contract ratio? If so to what color? 
It would be great if you could shed some light on the, please. 
Thanks

**Comment by wayungi** [comment]
Hello @porag-m06, I understand your concern at this point. Every milestone has its own requirements. In this particular milestone, we are checking for **accessibility** and, in this case, **contrast**. Please go ahead and change the colours if it will improve the contrast but I suggest you vary the intensity of the colour until an acceptable contrast level is reached. 

- [OPTIONAL ] If you choose to change the colour,  I suggest you choose a colour that fits well with the existing colours on the page so that your site still remains esthetically appealing

**Comment by porag-m06** [comment]
Thanks a lot. It is much clear now.

**Review by Zuhaib042 — APPROVED** [review]
Hi @porag-m06 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
