### PR TITLE
Module 1: Block 4: Day 4

### PR DESCRIPTION
**Pull request by porag-m06**
Hello,
Here is my project for your kind review,

### Data save in localStorage in the browser
- All the data of the form are added into a single JavaScript object
- All input fields data is saved to the local storage
- All input fields data is populated from the local storage

### CODE REVIEW

**Review by jerryowusu — COMMENTED** [review]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

kpop-approved


## Highlights
:heavy_check_mark: Data preserved 
:heavy_check_mark: Used DOM manipulation

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by porag-m06** [comment]
Hello @jerryowusu, 
Thanks for the explanation. My partner contributed to this project initially but due to some conflicts I had to merge with the main branch with this branch and lost his contributions.

**Comment by sulaimanahmadi** [comment]
Hello @jerryowusu,
as far the pair programming rules I have contributed my part to the project


thank you

**Review by jerryowusu — COMMENTED** [review]
.

**Pull request merged**
